spring.application.name=movie-service

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/movie_streaming_web?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Custom JWT properties
jwt.signerKey=aVeryLongSecretKeyThatIsAtLeast32BytesLongForHS256Encryption!
jwt.valid-duration=86400
jwt.refreshable-duration=604800

# Pexels API Configuration
external.pexels.api-key=VRmeOeyvrg8FMM71poRRq1CCJCEnJ0IdvPft1mBo0uEePfbCXEgQ9Lnz
external.pexels.base-url=https://api.pexels.com
external.pexels.enabled=true